web/lights/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import views

urlpatterns = patterns('',

    url(r'^$', views.boutons, name='boutons'),
    url(r'^enable/$', views.enable, name='enable'),
)

web/serenity/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns_not_rooted = patterns('',
    # Examples:
    # url(r'^$', 'serenity.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('lights.urls', namespace="lights")),
)

urlpatterns = patterns('',
    url(r'^domo/', include(urlpatterns_not_rooted)),
)

web/lights/models.py
from django.db import models

# Create your models here.

web/lights/views.py
from django.shortcuts import render, redirect
import subprocess

BIN=['sudo', '-n', '/home/dstan/serenIT/domo/domo.py']
# Create your views here.

AVAILABLE = [1,2,3,4]

_enabled = { x: False for x in AVAILABLE}

def boutons(request):
    buttons = list()
    for i in AVAILABLE:
        buttons.append({'label': u'%d' % i, 'on': _enabled[i]})
    return render(request, 'index.html', {'buttons': buttons})

def enable(request):
    try:
        num = int(request.POST['num'])
    except Exception:
        num = None
    if num not in AVAILABLE:
        num = AVAILABLE[0]
    _enabled[num] = not _enabled[num]
    arg = '%s:%d' % (('on' if _enabled[num] else 'off'), num)
    subprocess.check_output(BIN + [arg])
    return redirect('lights:boutons')
    

web/lights/templates/index.html
{% load url from future %}
<html>
<head>
<title>Serenity</title>
<style type="text/css">
body {
  margin: 0;
  padding: 0;
}

.bouton {
  margin: 0;
  padding: 0;
  width: 50%;
  height: 50%;
  float: left;
  font-size: 10em;
  background-color: white;
}

.bouton.on {
  background-color: yellow;
}

</style>
</head>
<body>
<form method="post" action="{% url 'lights:enable' %}">
{% csrf_token %}
{% for button in buttons %}
<input type="submit" class="bouton{% if button.on %} on{% endif %}" name="num" value="{{ button.label }}" />
{% endfor %}
</body>
</body>
</html>